
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 21 17:59:44 CET 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 32;
  public static final int EGAL = 28;
  public static final int OU = 26;
  public static final int PLUS = 11;
  public static final int LIRE = 29;
  public static final int SUP = 21;
  public static final int ECRIRE = 2;
  public static final int ALORS = 18;
  public static final int TANTQUE = 7;
  public static final int REPETER = 8;
  public static final int CHAINECARACTERE = 33;
  public static final int NON = 27;
  public static final int FSI = 20;
  public static final int INF = 22;
  public static final int MOINS = 12;
  public static final int POINTVIRGULE = 3;
  public static final int FINTANTQUE = 9;
  public static final int PARFER = 16;
  public static final int SINON = 19;
  public static final int ENTIER = 6;
  public static final int EOF = 0;
  public static final int MULT = 13;
  public static final int EGALEGAL = 23;
  public static final int DIV = 14;
  public static final int CONSTANTEBOOL = 31;
  public static final int ET = 25;
  public static final int SI = 17;
  public static final int error = 1;
  public static final int PAROUV = 15;
  public static final int DIFF = 24;
  public static final int CONSTANTEINT = 30;
  public static final int DEBUT = 5;
  public static final int FIN = 10;
  public static final int PROGRAMME = 4;
}

