
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 13 09:41:38 CET 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 22;
  public static final int OU = 18;
  public static final int PLUS = 7;
  public static final int SUP = 13;
  public static final int ECRIRE = 2;
  public static final int CHAINECARACTERE = 23;
  public static final int NON = 19;
  public static final int MOINS = 8;
  public static final int INF = 14;
  public static final int POINTVIRGULE = 3;
  public static final int PARFER = 12;
  public static final int EOF = 0;
  public static final int MULT = 9;
  public static final int EGALEGAL = 15;
  public static final int DIV = 10;
  public static final int CONSTANTEBOOL = 21;
  public static final int ET = 17;
  public static final int error = 1;
  public static final int PAROUV = 11;
  public static final int DIFF = 16;
  public static final int CONSTANTEINT = 20;
  public static final int DEBUT = 5;
  public static final int FIN = 6;
  public static final int PROGRAMME = 4;
}

